apiVersion: v2
appVersion: "1.0"
description: A Helm chart for jjj-jjj App
name: jjj-jjj
home: https://github.com/hmcts/jjj-jjj
version: 0.0.1
dependencies:
  - name: nodejs
    version: 2.3.1
    repository: '@hmctspublic'

